markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: wlyw
    description: Talk is cheap！
    title: wlyw的博客
    url: wlyw.github.io
    url_optional: page/category.html
    duoshuo: wlyw
    tongji: 2354fa504a8025f370c4408aeadfc611
    qiniu:
author:
    name: wlyw
    email: XXX@gmail.com
    weibo: http://weibo.com/u/2058535374
    github: https://github.com/wlyw
    logo: /res/img/wlyw.jpg
    douban:
        name: 52750905
        key: 06ee34725a0e447a14ca9d570e2acd6e